### ISSUE TITLE
NYR cooldown timings from other source

### ISSUE THREAD

**Issue by korbel** [theckhd/ALIA#2]
Hi, I'm not sure if it's helpful for further polish this mod but it might be worth to compare the data in this mod to a comprehensive guide posted on [Agnitio forums](https://agnitiotsw.enjin.com/forum/m/21068189/viewthread/32574646-nyr-e10-lurker-mechanics) couple of years ago by player LadyPhoenix. It contains all the timings (and mechanics) specific to NYR E10 lurker.

![image](https://user-images.githubusercontent.com/638554/122668650-5fb84980-d1b9-11eb-84ff-663f834ef188.png)

**Comment by theckhd** [comment]
Most of these are already in the mod. I've had to empirically test most of them because some of the mechanics are different on E17 (and on lower difficulties, though I'm less concerned about those being very accurate at this point in the game's life cycle). I've also found some inconsistencies in the behavior that don't match what's described above, but that's perhaps to be expected since the devs messed around with Lurker's "brain" during the rebalance beta period as they added the E17 difficulty.
